05.Fiap.Web.MVC/05.Fiap.Web.MVC/Models/Comida.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _05.Fiap.Web.MVC.Models
{
    public class Comida
    {

        public string Nome { get; set; }
        public decimal Preco { get; set; }
        public bool Salgado { get; set; }
        public string Descricao { get; set; }
        public bool Vegetariano { get; set; }
        public double Calorias { get; set; }




    }
}

05.Fiap.Web.MVC/05.Fiap.Web.MVC/Controllers/ComidaController.cs
using _05.Fiap.Web.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _05.Fiap.Web.MVC.Controllers
{

    // Simular um banco de dados
    public class ComidaController : Controller

    {

        private static List<Comida> _banco = new List<Comida>();

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_banco); 
        }

        // GET: Comida
        [HttpGet]
        public ActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Index(Comida comida)
        {
            _banco.Add(comida);
            TempData["msg"] = "Comida cadastrada";
            return RedirectToAction("Listar");
        }


    }
}

05.Fiap.Web.MVC/05.Fiap.Web.MVC/Views/Comida/Index.cshtml
@model _05.Fiap.Web.MVC.Models.Comida

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>



@using (Html.BeginForm())
{


    <div class="form-group">

        <div class="form-group">
            @Html.LabelFor(churros => churros.Nome)
            @Html.TextBoxFor(c => c.Nome)
        </div>

        <div class="form-group">
            @Html.LabelFor(churros => churros.Preco)
            @Html.TextBoxFor(c => c.Preco)
        </div>


        <div class="form-group">
            @Html.CheckBoxFor(churros => churros.Vegetariano)
            @Html.LabelFor(c => c.Vegetariano)
        </div>

        <div class="form-group">
            @Html.CheckBoxFor(churros => churros.Salgado)
            @Html.LabelFor(c => c.Salgado)
        </div>

        <div class="form-group">
            @Html.LabelFor(churros => churros.Descricao)
            @Html.TextAreaFor(c => c.Descricao)
        </div>


        <div class="form-group">
            @Html.LabelFor(churros => churros.Calorias)
            @Html.TextBoxFor(c => c.Calorias)
        </div>

        <input type="submit" value="Cadastrar" class="btn btn-primary" />

    </div>

}

05.Fiap.Web.MVC/05.Fiap.Web.MVC/Views/Comida/Listar.cshtml
@model List<_05.Fiap.Web.MVC.Models.Comida>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>


@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

<table class="table">

    <tr>
        <th>Nome</th>
        <th>Calorias</th>
        <th>Preço</th>
        <th>Descrição</th>
        <th>Salgado</th>
        <th>Vegetariano</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Preco</td>
            <td>@item.Salgado</td>
            <td>@item.Vegetariano</td>
            <td>@item.Descricao</td>
            <td>@item.Calorias</td>
        </tr>

    }


</table>

05.Fiap.Web.MVC/05.Fiap.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP Food", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro de comida", "Index", "Comida")</li>
                    <li>@Html.ActionLink("Listar de Comidas", "Listar", "Comida")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>