Fiap06.Web.MVC/Fiap06.Web.MVC/Models/Bebida.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    [Table("TBebida")]
    public class Bebida
    {
        [Column("Id")]
        public int BebidaId { get; set; }

        [Required]
        [MaxLength(100)]
        public string Nome { get; set; }

        public bool Destilado { get; set; }

        [Display(Name = "Preço")]
        public decimal Preco { get; set; }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Models/Petisco.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    public class Petisco
    {        
        public int PetiscoId { get; set; }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Controllers/BebidaController.cs
using Fiap06.Web.MVC.Models;
using Fiap06.Web.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Web.MVC.Controllers
{
    public class BebidaController : Controller
    {
        private BotecoContext _context = new BotecoContext();

        // Realizando a pesquisa

        [HttpGet]

        public ActionResult Pesquisar(string nome)
        {
           var lista = _context.Bebidas.Where(e => e.Nome.Contains(nome)).ToList();
           //Retornando para a pagina listar com a lista de bebida
          return View("Listar",lista);
        }
     
        [HttpPost]
        public ActionResult Atualizar(Bebida bebida)
        {
            //Atualiza o banco de dados
            _context.Entry(bebida).State = EntityState.Modified;
            _context.SaveChanges();
            //Mensagem
            TempData["msg"] = "Bebida Atualizada!";
            //Redirecionar
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Atualizar(int id)
        {
            //Busca a bebida no banco de dados
            var bebida = _context.Bebidas.Find(id);
            //Retorna a view com o objeto bebida
            return View(bebida);
        }


        // Removendo , devo mandar um ID para a pagina que lista 
        // Utilizar o Post para privatizar a url

        [HttpPost]
        public ActionResult Excluir(int id)
        {
            // context é a classe contem as coleções para realizar o crud
            var bebida = _context.Bebidas.Find(id);
            _context.Bebidas.Remove(bebida);

            // Realizando o commit
            _context.SaveChanges();

            //Mandando msg
            TempData["msg"] = "Bebida Removida";
            return RedirectToAction("Listar");
        }

        // Listar

        [HttpGet]
        public ActionResult Listar()
        {
            //Recupera todas as bebidas e envia para a tela
            return View(_context.Bebidas.ToList());
        }


        // Exibindo

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        // Cadastrando

        [HttpPost]
        public ActionResult Cadastrar(Bebida bebida)
        {
            _context.Bebidas.Add(bebida);
            _context.SaveChanges();
            TempData["msg"] = "Bebida Cadastrada!";
            return RedirectToAction("Cadastrar");
        }




    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Web.MVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Bebida/Atualizar.cshtml
@model Fiap06.Web.MVC.Models.Bebida

@{
    ViewBag.Title = "Atualizar";
}

<h2>Atualizar Bebida</h2>

@using (Html.BeginForm())
{
    // Criar um atribudo escondido para ser recuperado

    @Html.HiddenFor(b => b.BebidaId)
    <div class="form-group">
        @Html.LabelFor(b => b.Nome)
        @Html.TextBoxFor(b => b.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(b => b.Preco)
        @Html.TextBoxFor(b => b.Preco, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(b => b.Destilado)
        @Html.LabelFor(b => b.Destilado)
    </div>

    <input type="submit" value="Editar" class="btn btn-primary" />
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Bebida/Cadastrar.cshtml
@model Fiap06.Web.MVC.Models.Bebida

@{
    /**/

    ViewBag.Title = "Cadastrar";
}

@if(TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

<h2>Cadastrar</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(b => b.Nome)
        @Html.TextBoxFor(b => b.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(b => b.Preco)
        @Html.TextBoxFor(b => b.Preco, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(b => b.Destilado)
        @Html.LabelFor(b => b.Destilado, new { @class = "form-control"})
    </div>
    <input type="submit" value="Cadastrar" id="btCadastro"/>
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Bebida/Listar.cshtml
@model List<Fiap06.Web.MVC.Models.Bebida>

@{
    ViewBag.Title = "Listar";
}

<h2>Lista de Bebidas</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}


<!-- Realizando pesquisa -->

@using (Html.BeginForm("Pesquisar","Bebida" , FormMethod.Get , new { @class = "form-inline" }))
{
<input type="text" name="nome" id="id_nome" class="form-control" placeholder="Digite o nome" />
<input type="submit" value="Pesquisar" class="btn btn-primary"/>
}

<table class="table table-striped">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Preço</th>
        <th>Destilado</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.BebidaId</td>
            <td>@item.Nome</td>
            <td>@item.Preco</td>
            <td>@item.Destilado</td>
            <td>
                @Html.ActionLink("Editar", "Atualizar", new { id = item.BebidaId }, new { @class = "btn btn-info btn-sm" })
            </td>
            <td>
                <!-- Recuperar o ID da bebida para ser excluido -->
                <!-- Recebe o id criado no input hidden e passar a variavel que esta representado o model ou seja o indice e chamar o atributo  -->
                <button onclick="codigoBebida.value = @item.BebidaId" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal">
                    Excluir
                </button>

            </td>
        </tr>

    }

</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Excluir</h4>
            </div>
            <div class="modal-body">
                Deseja Realmente apagar a bebida ? Isso é irrerverssível
            </div>
            <div class="modal-footer">

                <!-- Criando um formulario para realizar a ação -->
                <!-- Passar o nome do metodo que ira realizar a ação e nome do Controller -->
                @using (Html.BeginForm("Excluir", "Bebida"))
                {
                    // 1 - Criar um campo invisivel para realizar a exclusão
                    // 2 - Passar o name igual a assinatura feita no metodo excluir
                    // 3 - Passar onclick no modal no botao excluir
                    <input type="hidden" name="id" id="codigoBebida"/>

                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <!-- Passar o tipo de atributo para ele dar o realod -->
                    <button type="submit" class="btn btn-primary">Excluir</button>
                }
            </div>
        </div>
    </div>
</div>

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@section scripts{
    <p>Conteúdo na section scripts...</p>
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro Bebida","Cadastrar","Bebida")</li>
                    <li>@Html.ActionLink("Bebidas","Listar","Bebida")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    
    <!--Área para as páginas adicionarem conteúdo-->
    @RenderSection("scripts",false)

</body>
</html>